language: java

jdk:
  - oraclejdk8

dist: trusty
addons:
  apt:
    packages:
      oracle-java8-installer

before_install:
  - git clone https://github.com/davherrmann/immutable.git
  - cd immutable
  - mvn clean install

after_success:
  - mvn clean test jacoco:report coveralls:report
